[skip-deploy] CI: Update global workflows

diff --git a/.github/workflows/wp-engine.yml b/.github/workflows/wp-engine.yml
--- a/.github/workflows/wp-engine.yml
+++ b/.github/workflows/wp-engine.yml
@@ -1,55 +1,76 @@
-# This action is centrally managed in https://github.com/designcontainer/.github/
-# Don't make changes to this file outside of the .github repository!
-# Files will get overwritten with changes made to the same file in the above mentioned repository.
-
-name: Deploy to WP Engine & Notify Slack
+name: Github to WPE deployer
 
 on:
-    push:
-        branches:
-            - master
-            - staging
-            - development
+  push:
+    branches:
+      - master
+      - staging
+      - development
 
 jobs:
-    build:
-        if: "github.event.repository.name != '.github' && github.event.repository.name != 'wpe-template' && !contains(github.event.head_commit.message, '[skip deploy]') && !contains(github.event.head_commit.message, '[skip-deploy]')"
-        runs-on: ubuntu-latest
+  deploy:
+    if: "github.event.repository.name != '.github' && github.event.repository.name != 'wpe-template' && !contains(github.event.head_commit.message, '[skip-deploy]')"
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
 
-        steps:
-            - uses: actions/checkout@v2
-            - name: Get install for deployer by branch
-              id: get_install
-              uses: designcontainer/wpe-install-by-branch@master
-              with:
-                  wpe_api_key_pub: ${{ secrets.WPE_API_USERNAME }}
-                  wpe_api_key_priv: ${{ secrets.WPE_API_PASSWORD }}
+      - name: Get install for deployer by branch
+        id: get_install
+        uses: designcontainer/wpe-install-by-branch@master
+        with:
+          wpe_api_key_pub: ${{ secrets.WPE_API_USERNAME }}
+          wpe_api_key_priv: ${{ secrets.WPE_API_PASSWORD }}
 
-            - uses: actions/checkout@v2
-            - name: GitHub Deploy to WP Engine
-              uses: wpengine/github-action-wpe-site-deploy@v2.3.5
-              with:
-                  WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_PRIVATE_KEY_NAME }}
-                  PRD_BRANCH: master
-                  PRD_ENV: ${{ steps.get_install.outputs.install }}
-                  STG_BRANCH: staging
-                  STG_ENV: ${{ steps.get_install.outputs.install }}
-                  DEV_BRANCH: development
-                  DEV_ENV: ${{ steps.get_install.outputs.install }}
-              env:
-                  WPE_ENV_NAME: ${{ steps.get_install.outputs.install }}
-                  WPE_SSHG_KEY_PUBLIC: ${{ secrets.WPE_PUBLIC_KEY_NAME }}
-                  WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_PRIVATE_KEY_NAME }}
+      - name: Add ssh stuff
+        run: |
+          mkdir ~/.ssh/
+          eval `ssh-agent -s` # Start our SSH agent
+          echo "${{ secrets.WPE_SSH_KEY_PRIVATE }}" > ~/.ssh/id_rsa
+          echo "${{ secrets.WPE_SSH_KEY_PUBLIC }}" > ~/.ssh/id_rsa.pub
+          chmod 700 ~/.ssh
+          chmod 600 ~/.ssh/id_rsa
+          chmod 644 ~/.ssh/id_rsa.pub
+          ssh-keyscan -t rsa "git.wpengine.com" >> ~/.ssh/known_hosts # Add git server/url to known hosts
+          ssh-keygen -R "${{ steps.get_install.outputs.install }}.ssh.wpengine.net" # Not sure if this is needed :P
+          ssh-add # Not sure if this is needed :P
 
-            - uses: actions/checkout@v2
-            - name: Slack Notification
-              uses: rtCamp/action-slack-notify@v2
-              env:
-                  SLACK_CHANNEL: dc-github
-                  SLACK_COLOR: ${{job.status}}
-                  SLACK_ICON: https://github.com/designcontainer.png?size=48
-                  SLACK_TITLE: Commit message
-                  SLACK_USERNAME: DC Github Bot
-                  SLACK_FOOTER: This commit has been deployed to ${{ github.event.repository.name }}
-                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-                  MSG_MINIMAL: commit
+      - name: Set git stuff
+        run: |
+          git config --global user.email 'tech@designcontainer.no'
+          git config --global user.name 'designcontainer-bot'
+          git config core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=~/.ssh/known_hosts"
+          git remote add wpe git@git.wpengine.com:production/${{ steps.get_install.outputs.install }}.git
+
+      - name: PHP Lint
+        if: "contains(github.event.head_commit.message, '[php-lint]') "
+        run: |
+          echo "Begin PHP Linting."
+          find ./ -name "*.php" -type f -print0 | while IFS= read -r -d '' file; do
+              php -l "$file"
+              status=$?
+              if [[ $status -ne 0 ]]; then
+                  echo "FAILURE: Linting failed - $file :: $status" && exit 1
+              fi
+          done
+          echo "PHP Lint Successful! No errors detected!"
+
+      - name: Composer update
+        if: "contains(github.event.head_commit.message, '[composer-update]') "
+        run: composer update
+
+      - name: Deploy to WPE
+        run: git push -f wpe HEAD:main
+
+      - name: Slack Notification
+        uses: rtCamp/action-slack-notify@v2
+        env:
+          SLACK_CHANNEL: dc-github
+          SLACK_COLOR: ${{job.status}}
+          SLACK_ICON: https://github.com/designcontainer.png?size=48
+          SLACK_TITLE: Commit message
+          SLACK_USERNAME: DC Github Bot
+          SLACK_FOOTER: This commit has been deployed to ${{ github.event.repository.name }}
+          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+          MSG_MINIMAL: commit
